version: '3.3'
services:
  hdfs-namenode:
    build: ./hadoop
    command: /usr/local/hadoop/bin/hdfs namenode
    ports:
      - "8020"
      - target: 9000
        published: 9000
      - "50010"
      - "50020"
      - target: 50070
        published: 50070
      - "50075"
      - "50090"
  hdfs-datanode:
    build: ./hadoop
    command: /usr/local/hadoop/bin/hdfs datanode
    depends_on:
      - hdfs-namenode
    ports:
      - target: 50075
        published: 50075
  yarn-resourcemanager:
    build: ./hadoop
    command: /usr/local/hadoop/bin/yarn resourcemanager
    ports:
      - "8030"
      - "8031"
      - target: 8032
        published: 8032
      - "8033"
      - "8040"
      - target: 8088
        published: 8088
    depends_on:
      - hdfs-namenode
      - hdfs-datanode
  yarn-node:
    build: ./hadoop
    command: /usr/local/hadoop/bin/yarn nodemanager
    depends_on:
      - yarn-resourcemanager
      - hdfs-namenode
      - hdfs-datanode
    ports:
      - target: 8042
        published: 8042
  spark:
    build: ./hadoop
    depends_on:
      - yarn-resourcemanager
      - yarn-node
      - hdfs-namenode
      - hdfs-datanode
    volumes:
      - ./spark:/spark:rw


